db_driver=com.mysql.cj.jdbc.Driver
db_url=jdbc:mysql://localhost:3306/livedb2?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
db_user=root
db_password=SMmar@2021